[{"line":2,"elements":[{"start_timestamp":"2023-01-22T07:50:18.559Z","line":5,"name":"Login Functionality","description":"","id":"to-login-functionality;login-functionality","type":"scenario","keyword":"Scenario","steps":[{"result":{"duration":1569001000,"status":"passed"},"line":6,"name":"user Must Launch Url In The Url Field","match":{"location":"com.stepdefinitions.RW_Login.user_must_launch_url_in_the_url_field()"},"after":[{"result":{"duration":8010700,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"Given "},{"result":{"duration":742996400,"status":"passed"},"line":7,"name":"user Enter The Username In The Username Field","match":{"location":"com.stepdefinitions.RW_Login.user_enter_the_username_in_the_username_field()"},"after":[{"result":{"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"When "},{"result":{"duration":226000000,"status":"passed"},"line":8,"name":"user Enter The Password In The Password Field","match":{"location":"com.stepdefinitions.RW_Login.user_enter_the_password_in_the_password_field()"},"after":[{"result":{"duration":999400,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"And "},{"result":{"duration":416492000,"status":"passed"},"line":9,"name":"user must unselect default business unit","match":{"location":"com.stepdefinitions.RW_Login.user_must_unselect_default_business_unit()"},"after":[{"result":{"duration":2000400,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"And "},{"result":{"duration":111007000,"status":"passed"},"line":10,"name":"user Click The Singin Botton and It Navigates To The Netmeds RWOS Page","match":{"location":"com.stepdefinitions.RW_Login.user_click_the_singin_botton_and_it_navigates_to_the_netmeds_rwos_page()"},"after":[{"result":{"duration":999000,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"And "},{"result":{"duration":767902900,"status":"passed"},"line":11,"name":"user if already login click the yes botton","match":{"location":"com.stepdefinitions.RW_Login.user_if_already_login_click_the_yes_botton()"},"after":[{"result":{"duration":1994500,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"Then "}],"tags":[{"name":"@Login_page"}]},{"start_timestamp":"2023-01-22T07:50:23.420Z","line":13,"name":"Select Business Unit","description":"","id":"to-login-functionality;select-business-unit","type":"scenario","keyword":"Scenario","steps":[{"result":{"duration":638214100,"status":"passed"},"line":14,"name":"User Must Select Common Business Unit","match":{"location":"com.stepdefinitions.RW_Login.user_must_select_common_business_unit()"},"after":[{"result":{"duration":1003900,"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"Given "},{"result":{"duration":207999300,"status":"passed"},"line":15,"name":"user click the process button","match":{"location":"com.stepdefinitions.RW_Login.user_click_the_process_button()"},"after":[{"result":{"status":"passed"},"match":{"location":"com.stepdefinitions.RW_Login.checkingScenario(io.cucumber.java.Scenario)"}}],"keyword":"When "}],"tags":[{"name":"@Login_page"}]}],"name":"To Login Functionality","description":"  ------------","id":"to-login-functionality","keyword":"Feature","uri":"file:feature/01_RW_Login.feature","tags":[{"name":"@Login_page","type":"Tag","location":{"line":1,"column":1}}]},{"line":1,"elements":[{"start_timestamp":"2023-01-22T07:50:24.308Z","line":2,"name":"Failure while executing Cucumber","description":"","id":"failure;failure-while-executing-cucumber","type":"scenario","keyword":"Scenario","steps":[{"result":{"duration":0,"status":"passed"},"line":3,"name":"Cucumber failed while executing","match":{"arguments":[],"location":"io.cucumber.core.Failure.failure_while_executing_cucumber()"},"keyword":"When "},{"result":{"duration":0,"error_message":"io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.\r\n\tat io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)\r\n\tat io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)\r\n\tat io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:97)\r\n\tat io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:145)\r\n\tat io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:57)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:222)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\r\n\tat org.testng.TestRunner.run(TestRunner.java:601)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n\tSuppressed: java.lang.NullPointerException: Cannot invoke \"java.lang.Throwable.getMessage()\" because \"error\" is null\r\n\t\tat runner.MyTestListener.handleTestCaseFinished(MyTestListener.java:42)\r\n\t\tat io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)\r\n\t\tat io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)\r\n\t\tat io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)\r\n\t\tat io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:62)\r\n\t\tat io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:218)\r\n\t\tat io.cucumber.core.runner.TestCase.run(TestCase.java:98)\r\n\t\tat io.cucumber.core.runner.Runner.runPickle(Runner.java:75)\r\n\t\tat io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)\r\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)\r\n\t\tat io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)\r\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)\r\n\t\tat io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)\r\n\t\tat io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)\r\n\t\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\t\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\t\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\t\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\t\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\t\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\t\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\t\t... 16 more\r\n\tSuppressed: java.lang.NullPointerException: Cannot invoke \"java.lang.Throwable.getMessage()\" because \"error\" is null\r\n\t\tat runner.MyTestListener.handleTestCaseFinished(MyTestListener.java:42)\r\n\t\tat io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)\r\n\t\tat io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)\r\n\t\tat io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)\r\n\t\tat io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:62)\r\n\t\tat io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:218)\r\n\t\tat io.cucumber.core.runner.TestCase.run(TestCase.java:98)\r\n\t\tat io.cucumber.core.runner.Runner.runPickle(Runner.java:75)\r\n\t\tat io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)\r\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)\r\n\t\tat io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)\r\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)\r\n\t\tat io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)\r\n\t\tat io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)\r\n\t\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\t\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\t\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\t\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\t\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\r\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\t\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\t\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\t\t... 16 more\r\n","status":"failed"},"line":4,"name":"Cucumber will report this error:","match":{"arguments":[],"location":"io.cucumber.core.Failure.cucumber_reports_this_error()"},"keyword":"Then "}]}],"name":"Test run failed","description":"There were errors during the execution","id":"failure","keyword":"Feature","uri":"classpath:io/cucumber/core/failure.feature","tags":[]}]